### ISSUE TITLE
make sure you pick the correct temperature

### ISSUE THREAD

**Issue by mavrothal** [01micko/pmcputemp#3]
https://github.com/01micko/pmcputemp/blob/ce6965822537b6922f2569bcfd9bdf82bd0935d0/pmcputemp.sh#L53
I'm not sure if is the Mac, the newer kernels, the acpi or something else but the script in a MacBook running Xenial with the 4.9.58 kernel picks up the battery temperature instead of the cpu temperature.
The patch bellow fixes that but I'm not sure if it is of general use.
```
--- a/usr/bin/pmcputemp.sh
+++ b/usr/bin/pmcputemp.sh
@@ -44,10 +44,10 @@
 	fi
 	[ ! -d $TMP ] && mkdir $TMP
 	for a in `find /sys/devices/virtual -type f -name 'temp'|sort` \
-			`find /sys/devices/platform -type f -name 'temp*_input'|sort` \
+			`find /sys/devices/platform/coretemp.0 -type f -name 'temp*_input'|sort` \
 			`find /sys/devices/pci* -type f -name 'temp*_input'|sort`
 	do find_func "$a"
-		[ -z "$FILE" ] && continue || break
+		[ -z "$FILE" -o "$(grep ^BAT $(dirname $FILE)/type)" != "" ] && continue || break
 	done
 	if [ ! "$FILE" ];then echo "Failed to find file" && exit 1
 	fi
```
Is an unlikely target but still you might want to consider when you have the chance.

**Comment by 01micko** [comment]
This should be fixed now.
